name: Container

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2.4.4
          - 2.5-beta3

    env:
      DEFAULT_VERSION: 2.4.4

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/setup-qemu-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: make icecast-${{ matrix.version }}.tar.gz

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/icecast
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=${{ matrix.version }}
            type=raw,value=latest,enable=${{ matrix.version == env.DEFAULT_VERSION }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
